/*
 * Argo Server API
 * You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`
 *
 * The version of the OpenAPI document: v2.11.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.GrpcGatewayRuntimeStreamError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StreamResultOfIoK8sApiCoreV1Event
 */
public class StreamResultOfIoK8sApiCoreV1EventTest {
    private final StreamResultOfIoK8sApiCoreV1Event model = new StreamResultOfIoK8sApiCoreV1Event();

    /**
     * Model tests for StreamResultOfIoK8sApiCoreV1Event
     */
    @Test
    public void testStreamResultOfIoK8sApiCoreV1Event() {
        // TODO: test StreamResultOfIoK8sApiCoreV1Event
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

}
